name: Checks

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: install checkers
      run: |
        pip install ruff isort mypy
    - name: ruff
      run: |
        ruff format . --diff
        ruff check . --diff
    - name: mypy
      run: mypy .
